// Wine list
const sampleWines = {
  wine1: {
    name: '"Diario" Branco, Vinho Verde DOC, 2021',
    type: "Белое, полусухое",
    region: "Португалия, Винью Верде",
    producer: "Vercoope",
    fortress: 9.5,
    volume: 0.75,
    grape: "Аринту, Лоурейру, Азаль Бранко",
    image: "/wine-images/Diario-Branco.jpg",
    price: 2891,
    status: "available",
  },

  wine2: {
    name: 'Turk, Gruner Veltliner Obere Kremser "Sandgrube" Reserve, 2018',
    type: "Белое, полусухое",
    region: "Австрия, Нижняя Австрия, Кремшталь",
    producer: "Turk",
    fortress: 13.5,
    volume: 0.75,
    grape: "Грюнер Вельтлинер: 100%",
    image: "/wine-images/Turk-Gruner-Veltliner.jpg",
    price: 3254,
    status: "available",
  },

  wine3: {
    name: 'Tamellini, "Le Bine de Costiola", Soave DOC Classico, 2019',
    type: "Белое, сухое",
    region: "Италия, Венето, Соаве",
    producer: "Tamellini",
    fortress: 12,
    volume: 0.75,
    grape: "Гарганега: 100%",
    image: "/wine-images/Le-Bine-de-Costiola.jpg",
    price: 3053,
    status: "available",
  },

  wine4: {
    name: 'Georg Breuer, Riesling "Venture", 2021',
    type: "Белое, полусухое",
    region: "Германия, Рейнгау",
    producer: "Georg Breuer",
    fortress: 11,
    volume: 0.75,
    grape: "Рислинг: 100%",
    image: "/wine-images/Georg-Breuer.jpg",
    price: 1750,
    status: "available",
  },

  wine5: {
    name: "Rene Lamy, Bourgogne AOC Chardonnay, 2016",
    type: "Белое, сухое",
    region: "Франция, Бургундия",
    producer: "Rene Lamy",
    fortress: 13,
    volume: 0.75,
    grape: "Шардоне: 100%",
    image: "/wine-images/Rene-Lamy.jpg",
    price: 2600,
    status: "available",
  },

  wine6: {
    name: 'Undurraga, "Aliwen" Cabernet Sauvignon-Syrah Reserva, 2021',
    type: "Красное, сухое",
    region: "Чили, Центральная Долина, Долина Мауле",
    producer: "Undurraga",
    fortress: 13.5,
    volume: 0.75,
    grape: "Каберне Совиньон, Сира",
    image: "/wine-images/Aliwen.jpg",
    price: 1658,
    status: "available",
  },

  wine7: {
    name: 'Pago Casa Gran, "Falcata" White, Valencia DO, 2021',
    type: "Белое, полусухое",
    region: "Испания, Валенсия",
    producer: "Pago Casa Gran",
    fortress: 12,
    volume: 0.75,
    grape: "Гевюрцтраминер, Москатель",
    image: "/wine-images/Falcata.jpg",
    price: 1350,
    status: "available",
  },

  wine8: {
    name: "Castello d'Albola, 'OSO', Toscana IGT, 2016",
    type: "Красное, сухое",
    region: "Италия, Тоскана, Тоскана IGT",
    producer: "Zonin",
    fortress: 13,
    volume: 0.75,
    grape: "Санджовезе: 60%, Мерло: 20%, Сира: 20%",
    image: "/wine-images/OSO.jpg",
    price: 1430,
    status: "available",
  },

  wine9: {
    name: 'Domaine Mongeard-Mugneret, Coteaux Bourguignons "La Superbe" AOC, 2019',
    type: "Красное, сухое",
    region: "Франция, Бургундия",
    producer: "Mongeard-Mugneret",
    fortress: 14.5,
    volume: 0.75,
    grape: "Гаме: 70%, Пино Нуар: 30%",
    image: "/wine-images/Mongeard-Mugneret.jpg",
    price: 3000,
    status: "available",
  },
};

export default sampleWines;
